### ISSUE TITLE
Running Speed

### ISSUE THREAD

**Issue by Akina2001** [phs008/superpoint_libtorch#3]
opencv 4.2
libtorch 1.12.1 
cuda 11.3 
RTX 3080
Why does it take longer, almost 1s per frame

**Comment by Akina2001** [comment]
Why is libtorch's superpoint running faster than python's superpoint? It stands to reason that libtorch should be faster

**Comment by S1aoXuan** [comment]
> opencv 4.2 libtorch 1.12.1 cuda 11.3 RTX 3080 Why does it take longer, almost 1s per frame

Hi, did you successfully run the main.cpp? 
My platform is cuda 11.3 and libtorch 1.12.0. But when I run the main.cpp, I always get c10::Error. 
Do you know how to fix it? It troubles me a long time.

**Comment by Akina2001** [comment]
> > opencv 4.2 libtorch 1.12.1 cuda 11.3 RTX 3080 Why does it take longer, almost 1s per frame
> 
> Hi, did you successfully run the main.cpp? My platform is cuda 11.3 and libtorch 1.12.0. But when I run the main.cpp, I always get c10::Error. Do you know how to fix it? It troubles me a long time.


Sorry, I forgot how to fix it, but the following implementation will be better.
https://github.com/mingjitianming/superglue_apply

**Comment by S1aoXuan** [comment]
> > > opencv 4.2 libtorch 1.12.1 cuda 11.3 RTX 3080 Why does it take longer, almost 1s per frame
> > 
> > 
> > Hi, did you successfully run the main.cpp? My platform is cuda 11.3 and libtorch 1.12.0. But when I run the main.cpp, I always get c10::Error. Do you know how to fix it? It troubles me a long time.
> 
> Sorry, I forgot how to fix it, but the following implementation will be better. https://github.com/mingjitianming/superglue_apply

Thanks a lot. I will try this one!
